news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.home, name='home'),
    path('national', views.national, name='national'),
    path('international', views.international, name='international'),
    path('newsdetail/<int:id>', views.newsdetail, name='newsdetail'),
    path('search/', views.search, name='search'),

]

news_admin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.admin_dashboard, name='dashboard'),
    path('addnews', views.addnews, name='addnews'),

    # path('', views.userlogin, name='login'),
    # path('logout', views.userlogout, name='logout')


]

yolonews/urls.py
from django.contrib import admin
from django.urls import path, include
from news import urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('news_user.urls','news_user'), namespace='news_user')),
    path('news/', include(('news.urls','news'), namespace='news')),
    path('admins/', include(('news_admin.urls','news_admin'), namespace='news_admin')),
    

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

news_admin/models.py
from django.db import models

# Create your models here.

news_admin/forms.py
from django import forms
from news.models import News



class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = "__all__"

news_admin/views.py
from django.shortcuts import render, redirect
from news.models import *
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import NewsForm



# Create your views here.


def admin_dashboard(request):
    subscribers=User.objects.filter(is_staff=0).count()
    reporters= Reporter.objects.all().count()
    admins= User.objects.filter(is_staff=1).count()
    news= News.objects.all().count()
    nationalnews= News.objects.filter(category=1).count()
    internationalnews= News.objects.filter(category=2).count()
    recentnews= News.objects.all().order_by('-id')[:10]


    context={
        'subscribers':subscribers,
        'reporters':reporters,
        'admins':admins,
        'news':news,
        'nationalnews':nationalnews,
        'internationalnews':internationalnews,
        'recentnews':recentnews


    }
    return render(request, 'news_admin/dashboard.html',context)

def addnews(request):
    if request.method == 'GET':
        form=NewsForm
        context={'form':form}
        return render(request, "news_admin/addnews.html", context)

    else:
        form = NewsForm(request.POST, request.FILES)
      
        if form.is_valid():
            form.save()
            print(form)
            messages.success(request, 'News added successfully!')
            return redirect('news_admin:dashboard')
        else:
            form=NewsForm
            context={'form':form}
            messages.error(request, 'Error in saving data!!')

            return render(request, "news_admin/addnews.html", context)
  
    

templates/news_admin/addReporter.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="alert alert-success py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3 class="text-center">Add Reporter</h3><hr>
    <div class="col-lg-8 mx-auto">
        <div class="border p-4">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token%}
                <table class="table ">
                    {{form.as_table}}
                    
        
                </table>
                <button type="submit" class="btn btn-success">Save</button>
            </form>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/addadmin.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="success_message py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3 class="text-center">Add Admin</h3><hr>
    <div class="col-lg-8 mx-auto">
        <div class="border p-4">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token%}
                <table class="table ">
                    {{form.as_table}}
                    
        
                </table>
                <button type="submit" class="btn btn-success">Save</button>
            </form>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/addnews.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="success_message py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3>Add News Article</h3><hr>
    <div class="col-lg-8 mx-auto">
        <div class="border p-4">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token%}
                <table class="table ">
                    {{form.as_table}}
                    
        
                </table>
                <button type="submit" class="btn btn-success">Save</button>
            </form>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/allAdmins.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="alert alert-success py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3  class="text-center" >All Admins</h3>
  
    <hr>
    <div class="col-lg-8 mx-auto">
        <div class="border p-4">
            <table class="table">
                <thead>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Joined Date</th>
                    <th>Last Active</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    {% for i in admins %}
                    <tr>
                        <td>{{i.id}}</td>
                        <td>{{i.username}}</td>
                        <td>{{i.date_joined}}</td>
                        <td>{{i.last_login}}</td>
                        <td>
                            <a href="{% url 'news_admin:deleteAdmin' i.id %}" onclick="return confirm('Remove Admin?')" class="btn btn-danger btn-sm">Delete Admin</a>
                        </td>
                    </tr>
                    {% empty%}
                    <p class="h4">No subscribers at all.</p>
                    {% endfor %}
                </tbody>

            </table>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/allinternational.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="alert alert-success py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3  class="text-center" >All International News</h3>
    <a href="{% url 'news_admin:addnews' %}" class="btn btn-outline-info col-lg-2 align-items-end"> + &nbsp; Add news</a>
  
    <hr>
    <div class="col-lg-12 mx-auto">
        <div class="border p-4">
            <div>
                <table class="table table-light">
                    <thead>
                      <tr>
                        <th scope="col">News ID:</th>
                        <th scope="col">Heading</th>
                        <th scope="col">Reporter</th>
                        <th scope="col">Date</th>
                       
                        <th scope="col">Update/Delete</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                        {% for i in news %}
                      <tr>
                        <th scope="row">{{i.id}}</th>
                        <td>{{i.heading|truncatechars:18}}</td>
                        <td>{{i.reporter.name}}</td>
                        <td>{{i.date}}</td>
                    
                        <td><a href="{% url 'news_admin:updatenews' i.id  %}" class="btn btn-primary btn-sm">Update</a>
                        <a href="{% url 'news_admin:deletenews' i.id  %}" onclick="return confirm('Delete news?')" class="btn btn-danger btn-sm">Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/allnational.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="alert alert-success py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3  class="text-center" >All National News</h3>
    <a href="{% url 'news_admin:addnews' %}" class="btn btn-outline-info col-lg-2 align-items-end"> + &nbsp; Add news</a>
  
    <hr>
    <div class="col-lg-12 mx-auto">
        <div class="border p-4">
            <div>
                <table class="table table-light">
                    <thead>
                      <tr>
                        <th scope="col">News ID:</th>
                        <th scope="col">Heading</th>
                        <th scope="col">Reporter</th>
                        <th scope="col">Date</th>
 
                        <th scope="col">Update/Delete</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                        {% for i in news %}
                      <tr>
                        <th scope="row">{{i.id}}</th>
                        <td>{{i.heading|truncatechars:18}}</td>
                        <td>{{i.reporter.name}}</td>
                        <td>{{i.date}}</td>
                
                        <td><a href="{% url 'news_admin:updatenews' i.id  %}" class="btn btn-primary btn-sm">Update</a>
                        <a href="{% url 'news_admin:deletenews' i.id  %}" onclick="return confirm('Delete news?')" class="btn btn-danger btn-sm">Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/allnews.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="alert alert-success py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3  class="text-center" >All News</h3>
    <a href="{% url 'news_admin:addnews' %}" class="btn btn-outline-info col-lg-2 align-items-end"> + &nbsp; Add news</a>
  
    <hr>
    <div class="col-lg-12 mx-auto">
        <div class="border p-4">
            <div>
                <table class="table table-light">
                    <thead>
                      <tr>
                        <th scope="col">News ID:</th>
                        <th scope="col">Heading</th>
                        <th scope="col">Reporter</th>
                        <th scope="col">Date</th>
                        <th scope="col">Category</th>
                        <th scope="col">Update/Delete</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                        {% for i in news %}
                      <tr>
                        <th scope="row">{{i.id}}</th>
                        <td>{{i.heading|truncatechars:18}}</td>
                        <td>{{i.reporter.name}}</td>
                        <td>{{i.date}}</td>
                        <td>{{i.category.category}}</td>
                        <td><a href="{% url 'news_admin:updatenews' i.id  %}" class="btn btn-primary btn-sm">Update</a>
                        <a href="{% url 'news_admin:deletenews' i.id  %}" onclick="return confirm('Delete news?')" class="btn btn-danger btn-sm">Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/allreporters.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="success_message py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3>All Reporters</h3>
    <div>
        <a href="{% url 'news_admin:addReporter' %}" class="btn btn-primary btn">Add reporter</a>
    </div>
    <hr>
    <div class="col-lg-8 mx-auto">
        <div class="border p-4">
            <table class="table">
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Joined Date</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    {% for i in reps %}
                    <tr>
                        <td>{{i.id}}</td>
                        <td>{{i.name}}</td>
                        <td>{{i.phone}}</td>
                        <td>{{i.joined_date}}</td>
                        <td>
                            <a href="{% url 'news_admin:updateReporter' i.id %}" class="btn btn-primary btn-sm">Update </a>
                            <a href="{% url 'news_admin:deleteReporter' i.id %}" onclick="return confirm('Delete Reporter?')" class="btn btn-danger btn-sm">Remove</a>

                        </td>
                    </tr>
                    {% empty%}
                    <p class="h4">No subscribers at all.</p>
                    {% endfor %}
                </tbody>

            </table>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/allsubs.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="success_message py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3  class="text-center" >All Subscribers</h3>
    
    <hr>
    <div class="col-lg-12 mx-auto">
        <div class="border p-4">
            <table class="table">
                <thead>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Joined Date</th>
                    <th>Last Active</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    {% for i in subs %}
                    <tr>
                        <td>{{i.id}}</td>
                        <td>{{i.username}}</td>
                        <td>{{i.date_joined}}</td>
                        <td>{{i.last_login}}</td>
                        <td>
                            <a href="{% url 'news_admin:upgrateAdmin' i.id %}" onclick="return confirm('Upgrade subscriber to admin?')" class="btn btn-primary btn-sm">Make admin</a>
                            <a href="{% url 'news_admin:deleteSub' i.id %}" onclick="return confirm('Delete subscriber?')" class="btn btn-danger btn-sm">Remove User</a>
                        </td>
                    </tr>
                    {% empty%}
                    <p class="h4 text-center text-primary">No subscribers at all.</p>
                    {% endfor %}
                </tbody>

            </table>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/dashboard.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<style>
    .card-body a{
    text-decoration:none;
    color:#fff;
    }
    .card-body a:hover{
    color:orange;
    }
</style>
<div class="container"><hr>
    <h2>Admin Dashboard</h2> <a href="{% url 'news_admin:addnews' %}" class="btn btn-outline-info col-lg-2 align-items-end"> + &nbsp; Add news</a>
    <hr>
  
    <div class="row">
        <div class="col">
    <div class="card text-white bg-primary mb-3" style="max-width: 35rem;">
        <div class="card-header text-center">Total Subscribers</div>
        <div class="card-body">
            <a href=""><h1 class="card-title text-center">{{subscribers}}</h1></a>
        </div>
    </div>
        </div>
        <div class="col">
            <div class="card text-white bg-warning mb-3" style="max-width: 35rem;">
                <div class="card-header text-center">Total Reporters</div>
                <div class="card-body">
                    <a href=""><h1 class="card-title text-center">{{reporters}}</h1></a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-white bg-success mb-3" style="max-width: 35rem;">
                <div class="card-header text-center">Total Admins</div>
                <div class="card-body">
                    <a href="/admin-dashboard/show-user"><h1 class="card-title text-center">{{admins}}</h1></a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card text-white bg-dark mb-3" style="max-width: 35rem;">
                <div class="card-header text-center">Total National News</div>
                <div class="card-body">
                    <a href="/admin-dashboard/show-user"><h1 class="card-title text-center">{{nationalnews}}</h1></a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-white bg-info mb-3" style="max-width: 35rem;">
                <div class="card-header text-center">Total International News</div>
                <div class="card-body">
                    <a href=""><h1 class="card-title text-center">{{internationalnews}}</h1></a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-white bg-danger mb-3" style="max-width: 35rem;">
                <div class="card-header text-center">All Total News</div>
                <div class="card-body">
                    <a href=""><h1 class="card-title text-center">{{news}}</h1></a>
                </div>
            </div>
        </div>
        
    </div>
   <hr>
   <h3> Recent news:</h3>
    <hr>

    <div>
        <table class="table table-light">
            <thead>
              <tr>
                <th scope="col">News ID:</th>
                <th scope="col">Heading</th>
                <th scope="col">Reporter</th>
                <th scope="col">Date</th>
                <th scope="col">Category</th>
              </tr>
            </thead>
            <tbody>
                {% for i in recentnews %}
              <tr>
                <th scope="row">{{i.id}}</th>
                <td>{{i.heading|truncatechars:18}}</td>
                <td>{{i.reporter.name}}</td>
                <td>{{i.date}}</td>
                <td>{{i.category.category}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
</div>

{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/updateReporter.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="alert alert-success py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3  class="text-center">Update Reporter</h3><hr>
    <div class="col-lg-8 mx-auto">
        <div class="border p-4">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token%}
                <table class="table ">
                    {{form.as_table}}
                    
        
                </table>
                <button type="submit" class="btn btn-success">Save</button>
            </form>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}

templates/news_admin/updatenews.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}

<div class="container">
    {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h6 class="success_message py-3 px-1 my-2 text-center">{{message}}</h6>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <p class="alert alert-danger py-3 px-1 my-2 text-center">{{message}}</p>
            {% endif %}
            {% endfor %}
    <h3  class="text-center" >Update Article</h3><hr>
    <div class="col-lg-8 mx-auto">
        <div class="border p-4">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token%}
                <table class="table ">
                    {{form.as_table}}
                    
        
                </table>
                <button type="submit" class="btn btn-success">Update</button>
            </form>

        </div>

    </div>
</div>
<br><br>
{% include 'news/footer.html'%}


  
    
{% endblock %}