news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.home, name='home'),
    path('national', views.national, name='national'),
    path('international', views.international, name='international'),
    path('newsdetail/<int:id>', views.newsdetail, name='newsdetail'),
    path('search/', views.search, name='search'),

]

news_admin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.admin_dashboard, name='dashboard'),
    path('addnews', views.addnews, name='addnews'),

    # path('', views.userlogin, name='login'),
    # path('logout', views.userlogout, name='logout')


]

news_user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('register', views.userregister, name='register'),
    path('', views.userlogin, name='login'),
    path('logout', views.userlogout, name='logout')


]

yolonews/urls.py
from django.contrib import admin
from django.urls import path, include
from news import urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('news_user.urls','news_user'), namespace='news_user')),
    path('news/', include(('news.urls','news'), namespace='news')),
    path('admins/', include(('news_admin.urls','news_admin'), namespace='news_admin')),
    

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

class Reporter(models.Model):
    name= models.CharField(max_length=80)
    email= models.EmailField()
    phone=models.CharField(max_length=15)
    profile=models.ImageField(upload_to='reporters_pp')
    joined_date= models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    @property
    def imageUrl(self):
        try:
            url=self.profile.url
        except:
            url=''
        return url


class Category(models.Model):
    category=models.CharField(max_length=50)

    def __str__(self):
        return self.category


class News(models.Model):
    date= models.DateField(auto_now_add=True)
    heading= models.CharField(max_length=300)
    details= models.TextField()
    photo= models.ImageField(upload_to='news_photos')
    reporter= models.ForeignKey(Reporter, on_delete=models.CASCADE)
    category= models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    recent= models.BooleanField(default=False)
   
    def __str__(self):
        return self.heading

    @property
    def imageUrl(self):
        try:
            url=self.photo.url
        except:
            url=''
        return url



    

news/views.py
from django.shortcuts import render

from news_user.auth import user_only
from .models import *
from django.db.models import Q
from django.contrib import messages
from .filters import NewsFilter


# Create your views here.
@user_only
def home(request):
    national_news = News.objects.filter(category=1).order_by("-id")[:10]
    international_news = News.objects.filter(category=2).order_by("-id")[:10]
    breaking_news = News.objects.filter(recent=True).order_by("-id")[:3]

    context = {
        "national_news": national_news,
        "international_news": international_news,
        "breaking_news": breaking_news,
    }

    return render(request, "news/home.html", context)


def national(request):
    news = News.objects.filter(category=1).order_by("-id")
    news_filter = NewsFilter(request.GET, queryset=news)
    news_final = news_filter.qs

    return render(
        request, "news/national.html", {"news": news_final, "news_filter": news_filter}
    )


def international(request):
    news = News.objects.filter(category=2).order_by("-id")
    news_filter = NewsFilter(request.GET, queryset=news)
    news_final = news_filter.qs

    return render(
        request,
        "news/international.html",
        {"news": news_final, "news_filter": news_filter},
    )


def newsdetail(request, id):
    news = News.objects.get(id=id)
    return render(request, "news/newsdetail.html", {"news": news})


def search(request):
    if request.method == "GET":
        query = request.GET["query"]

        if len(query) > 20:
            messages.warning(request, "Query is too long")
            news = News.objects.none()

        elif len(query) == 0 or len(query) < 2:
            news = News.objects.none()
            messages.error(request, "Type something")

        news = News.objects.filter(
            Q(date__icontains=query)
            | Q(heading__icontains=query)
            | Q(details__icontains=query)
        )
        context = {"news": news, "query": query}
        return render(request, "news/search.html", context)

templates/news/base.html
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>YoloNews</title>
  </head>

  <body>

    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="z-index: 10000;">
      <div class="container">
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'news_admin:dashboard'%}">Dashboard</a>
            </li>
            {%else%}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'news:home'%}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'news:national'%}"><i class="fas fa-igloo"></i> &nbsp National News</a></li>
                <li><a class="dropdown-item" href="{% url 'news:international'%}"><i class="fas fa-globe"></i> &nbsp International News   </a></li>

              </ul>
            </li>
            {%endif%}
           
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown mr-5">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                <i class="fas fa-user-circle"></i> &nbsp {{user.username}}
              </a>
              <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#"> Read later  &nbsp <i class="fas fa-clock"></i></a></li>
                <li><a class="dropdown-item" href="{% url 'news_user:logout'%}">Logout &nbsp <i class="fas fa-sign-out-alt"></i></a></li>

              </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'news_user:register'%}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'news_user:login'%}">Login</a>
            </li>

            {% endif %}
          </ul>


        </div>
      </div>
    </nav>
    

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"
    ></script>
    <script
    src="https://kit.fontawesome.com/60f8143899.js"
    crossorigin="anonymous"
  ></script>

      </body>

</html>
  {% block navbar%}
{% endblock %}

templates/news/footer.html
<footer class="text-center text-white" style="background-color: #f1f1f1;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-dark" href="">YoloGuysNepal</a>
  </div>
  <!-- Copyright -->
</footer>

templates/news/home.html
{% extends 'news/base.html'%}
{% load static %}
{% block navbar%}
{% include 'news/navbar.html' %}
<link rel="stylesheet" href="{% static 'news/owlcarousel/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'news/owlcarousel/owl.carousel.min.css' %}">


    <main class="container">
   
      <div class="breaking text-center">
        <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"
              aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1"
              aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2"
              aria-label="Slide 3"></button>
          </div>
          
          <div class="carousel-inner">
            {% for i in breaking_news%}
            <div class="carousel-item active" data-bs-interval="10000">
              <a href="">
                <img src="{{i.imageUrl}} "
                class="d-block w-100" alt="photo"  style="height: 60vh">
              </a>
              <div class="carousel-caption d-none d-md-block text-white">
                <h5>{{i.heading}}</h5>
                <p>{{i.details|truncatechars:100}}</p>
              </div>
            </div>
            {% endfor %}
          </div>

            
            
            
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>

            
            
            
        
        <hr>
      </div><br>
      <div class="nationalnews">
        <h3 class="text-left">National News &nbsp; <a class="btn btn-primary btn-sm" href="{% url 'news:national'%}">See all..</a></h3>
        <hr>

        <div class="owl-carousel owl-theme">
          {% for i in national_news%}
          <div class="item">
            <div class="card" style="width: 13rem; height:18rem">
              <img
                src="{{i.imageUrl}}"
                class="card-img-top" alt="pic" style="height: 8em;" >
              <div class="card-body">
                <h5 class="card-title">{{i.heading|truncatechars:30}}</h5>
                <h6 class="card-subtitle mb-2 text-muted text-left">{{i.date}}</h6><br>

                <a href="{% url 'news:newsdetail' id=i.id%}" class="btn btn-outline-primary btn-sm col-lg-12">Read more</a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <hr>
      </div><br><br><br>
      <div class="intnews">
        <h3 class="text-left">International News &nbsp; <a class="btn btn-primary btn-sm" href="{% url 'news:international'%}">See all..</a></h3>

        <hr>
        <div class="owl-carousel owl-theme">
          {% for i in international_news%}
          <div class="item">
            <div class="card" style="width: 13rem;height:18rem">
              <img
                src="{{i.imageUrl}}"
                class="card-img-top" alt="pic" style="height: 8em;" >
              <div class="card-body">
                <h5 class="card-title">{{i.heading|truncatechars:30}}</h5>
                <h6 class="card-subtitle mb-2 text-muted text-left">{{i.date}}</h6><br>

                <a href="{% url 'news:newsdetail' id=i.id%}" class="btn btn-outline-primary btn-sm col-lg-12">Read more</a>
              </div>
            </div>
          </div>
          {% endfor %}


        </div>
      </div><hr>

    </main><br><br><br>
{% include 'news/footer.html'%}


  
    <script src="{% static 'news/owlcarousel/jquery.min.js'%}"></script>
    <script src="{% static 'news/owlcarousel/owl.carousel.min.js'%}"></script>
    <script>
      $('.owl-carousel').owlCarousel({
        loop: false,
        margin: 10,
        nav: true,
        responsive: {
          0: {
            items: 2
          },
          600: {
            items: 3
          },
          1000: {
            items: 5
          }
        }
      })
    </script>
{% endblock %}

templates/news/international.html
{% extends 'news/base.html'%}
{% block navbar%}

    <title>National News</title>
    <style>
        a{
            text-decoration: none;
            color: black;
        }
        a:hover{
            color: blue;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light navbar-expand-lg sticky-top">
      <div class="container ">
        <a class="navbar-brand" href="#">YoloTechNews</a>

        <form class="d-flex col-lg-4 ms-auto" method="GET" >
            {{ news_filter.form }}
            <button type="submit" class="btn btn-primary btn-sm">Search</button>
        </form>

  
        </form>
      </div>
    </nav><br>
    
    <div class="container">
      <br />
      <h2>International News:</h2>
      <hr />
      <div class="border rounded p-4">
        <div class="newsitem row">
          {% for i in news %}
            <div class="col-lg-3 col-md-4 col-6">
              <div class="card" style="width: 13rem; height:18rem">
                <img
                  src="{{i.imageUrl}}"
                  class="card-img-top" alt="pic" style="height: 8em;" >
                <div class="card-body">
                  <h5 class="card-title">{{i.heading|truncatechars:30}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted text-left">{{i.date}}</h6><br>
  
                  <a href="{% url 'news:newsdetail' id=i.id%}" class="btn btn-outline-primary btn-sm col-lg-12 col-12 col-md-12">Read..</a>
                </div>
              </div>

            </div>

            {% endfor %}
            
     
          
          
        </div>
      </div>
    </div>

  {% endblock %}

templates/news/national.html
{% extends 'news/base.html'%}
{% block navbar%}

    <title>National News</title>
    <style>
        a{
            text-decoration: none;
            color: black;
        }
        a:hover{
            color: blue;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light navbar-expand-lg sticky-top">
      <div class="container ">
        <a class="navbar-brand" href="#">YoloTechNews</a>

        <form class="d-flex col-lg-4 ms-auto" method="GET" >

            {{ news_filter.form }}
            <button type="submit" class="btn btn-primary btn-sm ">Search</button>
        </form>

  
        </form>
      </div>
    </nav><br>
    <div class="container">
      
      <br />
      <h2>National News:</h2>
      <hr />
      <div class="border rounded p-4">
        <div class="newsitem row">
          {% for i in news %}
            <div class="col-lg-3 col-md-4 col-6">
              <div class="card" style="width: 13rem; height:18rem">
                <img
                  src="{{i.imageUrl}}"
                  class="card-img-top" alt="pic" style="height: 8em;" >
                <div class="card-body">
                  <h5 class="card-title">{{i.heading|truncatechars:30}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted text-left">{{i.date}}</h6><br>
  
                  <a href="{% url 'news:newsdetail' id=i.id%}" class="btn btn-outline-primary btn-sm col-lg-12 col-12 col-md-12">Read..</a>
                </div>
              </div>

            </div>

            {% endfor %}
            
     
          
          
        </div>
      </div>
    </div>

  {% endblock %}

templates/news/navbar.html
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
  </head>

  <body>


    <nav class="navbar navbar-light bg-light navbar-expand-lg sticky-top">
        <div class="container ">
          <a class="navbar-brand" href="#">YoloTechNews</a>
  
          <form class="d-flex col-lg-4 ms-auto" method="GET" action="search">
  
            <input class="form-control me-2" type="search" placeholder="Search news" aria-label="Search"  id='query' name='query'>
  
            <button class="btn btn-primary " type="submit">Search</button>
          </form>
        </div>
      </nav><br>
    
    

    

      </body>

</html>

templates/news/newsdetail.html
{% extends 'news/base.html'%}
{% block navbar%}


  </head>
  <body>
    {% include 'news/simnavbar.html'%}
    <div class="container">
        <div class="col-lg-12 mx-auto">
            <div class="border rounded p-4">
                
                <img src="{{news.imageUrl}}" class="img rounded me-3 mb-2" style="height: 40vh; width:40%; float:left; "  alt="pic">
                <p class="h2 m-2  float-left" style="  word-wrap:break-word;">{{news.heading}} </p>
                <p class=""><i>Reporter: &nbsp;{{news.reporter.name}} &nbsp; <i class="h6">({{news.date}})</i></i></p>
                <p class="m-3  float-left" style="  word-wrap:break-word; text-align:justify">{{news.details}}</p><br>
               

            </div>
        </div>
    </div>

  {% endblock %}

templates/news/readlater.html
{% extends 'news/base.html'%}
{% block navbar%}

    <title>National News</title>
    <style>
        a{
            text-decoration: none;
            color: black;
        }
        a:hover{
            color: blue;
        }
    </style>
  </head>
  <body>
    
    <div class="container">
      
      <br />
      <h2>Read Later</h2>
      <hr />
      <div class="border rounded p-4">
        <div class="newsitem row">
          {% for i in all %}
            <div class="col-lg-3 col-md-4 col-6">
              <div class="card" style="width: 13rem; height:18rem">
                <img
                  src="{{i.news.imageUrl}}"
                  class="card-img-top" alt="pic" style="height: 8em;" >
                <div class="card-body">
                  <h5 class="card-title">{{i.news.heading|truncatechars:30}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted text-left">{{i.news.date}}</h6><br>
                  
                  <a href="{% url 'news:newsdetail' id=i.news.id%}" class=" btn btn-group btn-outline-primary btn-sm ">Read..</a>
                  <a href="{% url 'news:removeReadlater' id=i.id%}" onclick="return confirm('Remove from read later?')" class=" btn btn-group btn-danger btn-sm ">Remove</a>
  
                  
                </div>
              </div>

            </div>
            {%empty%}
            <h4 class="text-center"> No articles.</h4>

            {% endfor %}
            
     
          
          
        </div>
      </div>
    </div>

  {% endblock %}

templates/news/search.html
{% extends 'news/base.html'%}
{% block navbar%}
{% include 'news/simnavbar.html'%}


  </head>
  <body>
    <div class="container">
        {% if news|length == 0 %}
        <h1>No result found for : <b class="text-primary">{{query}}</b></h1>
        {% for message in messages %}
        <div class="alert alert-warning">
            <a class="close" href="#" data-dismiss="alert">X</a>
            <strong>Message: </strong>{{ message }}
            
    
        </div>
        <h3>No results found for : <b class="text-primary">{{query}}</b></h3>
        <h4>Suggestions:</h4>
        <ul>
            <li>Try another keyword.</li>
           
        </ul>
        {% endfor %}
        {% else %}
        <h3>Search results for :<b class="text-primary">{{query}}</b></h3>
        <div class="border rounded p-4">
            <div class="newsitem row">
              {% for i in news %}
                <div class="col-lg-3 col-md-4 col-6">
                  <div class="card" style="width: 13rem; height:18rem">
                    <img
                      src="{{i.imageUrl}}"
                      class="card-img-top" alt="pic" style="height: 8em;" >
                    <div class="card-body">
                      <h5 class="card-title">{{i.heading|truncatechars:30}}</h5>
                      <h6 class="card-subtitle mb-2 text-muted text-left">{{i.date}}</h6><br>
      
                      <a href="{% url 'news:newsdetail' id=i.id%}" class="btn btn-outline-primary btn-sm col-lg-12 col-12 col-md-12">Read..</a>
                    </div>
                  </div>
    
                </div>
    
                {% endfor %}
                
         
              
              
            </div>
        </div>
{% endif%}

  {% endblock %}

templates/news/simnavbar.html
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    
  </head>

  <body>


    <nav class="navbar navbar-light bg-light navbar-expand-lg sticky-top">
        <div class="container ">
          <a class="navbar-brand" href="#">YoloTechNews</a>
  
          
        </div>
      </nav><br>
    
    



      </body>

</html>